#workaround to build travis
dist: precise
language: java
jdk:
  - oraclejdk8
env:
   mysql -u root -e "CREATE DATABASE db_point_control;"
   mysql -u root -e "GRANT ALL PRIVILEGES ON db_point_control.* TO 'travis'@'%';";
